Repository Team-ThinkSync/CartReverse-back, pull requests merged in 2025-03, with the labels that each got.

#49 33 feature 리뷰 관련 기능
  .env
  build.gradle
  docker-compose.yml
  src/main/java/com/project/webshopproject/ask/AskRepository.java
  src/main/java/com/project/webshopproject/ask/AskService.java
  src/main/java/com/project/webshopproject/ask/dto/AskRequestDto.java
  src/main/java/com/project/webshopproject/ask/entity/Ask.java
  src/main/java/com/project/webshopproject/auth/AuthController.java
  src/main/java/com/project/webshopproject/config/EmailConfig.java
  src/main/java/com/project/webshopproject/config/RedisConfig.java
  src/main/java/com/project/webshopproject/config/SwaggerConfig.java
  src/main/java/com/project/webshopproject/email/EmailController.java
  src/main/java/com/project/webshopproject/email/EmailService.java
  src/main/java/com/project/webshopproject/email/RedisService.java
  src/main/java/com/project/webshopproject/review/ReviewImageRepository.java
  src/main/java/com/project/webshopproject/review/ReviewRepository.java
  src/main/java/com/project/webshopproject/review/ReviewRestController.java
  src/main/java/com/project/webshopproject/review/ReviewService.java
  src/main/java/com/project/webshopproject/review/dto/ReviewRequestDto.java
  src/main/java/com/project/webshopproject/review/dto/ReviewResponseDto.java
  src/main/java/com/project/webshopproject/review/entity/Review.java
  src/main/java/com/project/webshopproject/review/entity/ReviewImage.java
  src/main/java/com/project/webshopproject/user/UserRepository.java
  src/main/java/com/project/webshopproject/user/UserService.java
  src/main/resources/application.yml
Labels: feature

#61 결제내역 기능 구현
  build.gradle
  src/main/java/com/project/webshopproject/config/PaymentConfig.java
  src/main/java/com/project/webshopproject/payment/PaymentController.java
  src/main/java/com/project/webshopproject/payment/PaymentService.java
  src/main/java/com/project/webshopproject/payment/dto/PaymentConfirmRequestDto.java
  src/main/java/com/project/webshopproject/payment/dto/PaymentCreateResponseDto.java
  src/main/java/com/project/webshopproject/payment/dto/PaymentSuccessResponseDto.java
  src/main/java/com/project/webshopproject/payment/entity/Payment.java
  src/main/java/com/project/webshopproject/payment/entity/PaymentStatus.java
  src/main/java/com/project/webshopproject/payment/repository/PaymentRepository.java
  src/main/java/com/project/webshopproject/product/ProductController.java
  src/main/java/com/project/webshopproject/product/ProductService.java
  src/main/java/com/project/webshopproject/product/dto/OrderProductRequestDto.java
  src/main/java/com/project/webshopproject/product/repository/ProductQueryRepository.java
  src/main/resources/application.yml
Labels: feature

#48 fix: imageUrl 추가
  .env
  src/main/java/com/project/webshopproject/ask/AskController.java
  src/main/java/com/project/webshopproject/ask/AskRepository.java
  src/main/java/com/project/webshopproject/ask/AskService.java
  src/main/java/com/project/webshopproject/ask/dto/AskRequestDto.java
  src/main/java/com/project/webshopproject/ask/dto/AskResponseDto.java
  src/main/java/com/project/webshopproject/ask/entity/Ask.java
  src/main/java/com/project/webshopproject/ask/entity/AskImage.java
  src/main/java/com/project/webshopproject/ask/entity/Category.java
  src/main/java/com/project/webshopproject/auth/AuthController.java
  src/main/java/com/project/webshopproject/user/UserRestController.java
Labels: feature

#63 58 feature 회원 수정 및 전체조회
  src/main/java/com/project/webshopproject/ask/AskController.java
  src/main/java/com/project/webshopproject/cart/CartRepository.java
  src/main/java/com/project/webshopproject/cart/CartRestController.java
  src/main/java/com/project/webshopproject/cart/CartService.java
  src/main/java/com/project/webshopproject/review/ReviewRepository.java
  src/main/java/com/project/webshopproject/review/ReviewRestController.java
  src/main/java/com/project/webshopproject/review/ReviewService.java
  src/main/java/com/project/webshopproject/user/UserRepository.java
  src/main/java/com/project/webshopproject/user/UserRestController.java
  src/main/java/com/project/webshopproject/user/UserService.java
  src/main/java/com/project/webshopproject/user/dto/UserDto.java
  src/main/java/com/project/webshopproject/user/dto/UserGetResponseDto.java
  src/main/java/com/project/webshopproject/user/dto/UserUpdateRequestDto.java
  src/main/java/com/project/webshopproject/user/entity/User.java
Labels: feature

#57 좋아요 기능
  src/main/java/com/project/webshopproject/category/CategoryService.java
  src/main/java/com/project/webshopproject/category/entity/CategoryType.java
  src/main/java/com/project/webshopproject/like/LikeController.java
  src/main/java/com/project/webshopproject/like/LikeService.java
  src/main/java/com/project/webshopproject/like/dto/LikeRequestDto.java
  src/main/java/com/project/webshopproject/like/entity/LikeType.java
  src/main/java/com/project/webshopproject/like/entity/Likes.java
  src/main/java/com/project/webshopproject/like/repository/LikeRepository.java
  src/main/java/com/project/webshopproject/product/ProductService.java
  src/main/java/com/project/webshopproject/product/dto/ProductFindResponseDto.java
  src/main/java/com/project/webshopproject/product/dto/ProductResponseDto.java
  src/main/java/com/project/webshopproject/product/repository/ProductQueryRepository.java
  src/main/java/com/project/webshopproject/product/repository/ProductRepository.java
  src/main/java/com/project/webshopproject/review/ReviewRepository.java
  src/main/java/com/project/webshopproject/review/ReviewService.java
  src/main/java/com/project/webshopproject/review/dto/ReviewResponseDto.java
  src/main/java/com/project/webshopproject/user/UserRestController.java
  src/main/java/com/project/webshopproject/user/UserService.java
  src/main/java/com/project/webshopproject/user/dto/MyPageResponseDto.java
Labels: feature

#65 refactor: yml 파일 수정 및 각 파일 repository 메서드 명 변경
  src/main/java/com/project/webshopproject/ask/AskRepository.java
  src/main/java/com/project/webshopproject/ask/AskService.java
  src/main/java/com/project/webshopproject/ask/dto/AskRequestDto.java
  src/main/java/com/project/webshopproject/ask/dto/AskResponseDto.java
  src/main/java/com/project/webshopproject/ask/entity/Ask.java
  src/main/java/com/project/webshopproject/ask/entity/AskCategory.java
  src/main/java/com/project/webshopproject/category/CategoryService.java
  src/main/java/com/project/webshopproject/config/PaymentConfig.java
  src/main/java/com/project/webshopproject/config/WebClientConfig.java
  src/main/java/com/project/webshopproject/like/repository/LikeRepository.java
  src/main/java/com/project/webshopproject/payment/PaymentService.java
  src/main/java/com/project/webshopproject/payment/repository/PaymentRepository.java
  src/main/java/com/project/webshopproject/product/repository/ProductRepository.java
  src/main/java/com/project/webshopproject/review/ReviewService.java
  src/main/java/com/project/webshopproject/user/UserRepository.java
  src/main/java/com/project/webshopproject/user/UserService.java
  src/main/resources/application.yml
Labels: refactor

#69 58 refactor JPAAuditing 추가 및 상품, 카테고리 조회 권한 Public으로 수정
  src/main/java/com/project/webshopproject/WebShopProjectApplication.java
  src/main/java/com/project/webshopproject/config/WebSecurityConfig.java
Labels: refactor

#73 refactor: 스웨거 문서용 mock 로그인 API 추가
  src/main/java/com/project/webshopproject/auth/AuthController.java
Labels: feature, refactor
